### ISSUE TITLE
Mean vs median explorer broken on Firefox

### ISSUE THREAD

**Issue by nerik** [johnburnmurdoch/johnburnmurdoch.github.io#1]
I really like this little tool, but it's broken on my favourite browser :)
(Firefox 41, OSX)

**Comment by johnburnmurdoch** [comment]
Hi Erik, thanks for letting me know! I'll look into this and fix ASAP

**Comment by johnburnmurdoch** [comment]
Hi Erik, belatedly got around to this, and it should now be working properly on Firefox. Please let me know if not, and thanks again for flagging :-)

**Comment by nerik** [comment]
Great, thanks !
